name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Express.js 서버가 사용하는 Node.js 버전

    - name: Install dependencies
      run: |
        npm ci
        npm run build # 필요 시 빌드 스크립트 추가

    - name: Zip application
      run: zip -r app.zip .

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
        EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "$EB_APP_NAME" \
          --version-label "build-${{ github.run_number }}" \
          --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ github.run_id }}",S3Key="app.zip"

        aws elasticbeanstalk update-environment \
          --application-name "$EB_APP_NAME" \
          --environment-name "$EB_ENV_NAME" \
          --version-label "build-${{ github.run_number }}"
