name: Deploy to Amazon Web Service Elastic Beanstalk

on:
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS 자격 증명 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Amazon ECR Public에 로그인
    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n1b7r8u0

    # 4. Docker 이미지 빌드 및 푸시
    - name: Build, tag, and push image to Amazon ECR Public
      env:
        ECR_REGISTRY: public.ecr.aws/n1b7r8u0
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    # 5. Elastic Beanstalk 배포를 위한 패키지 생성
    - name: Prepare deployment package
      run: |
        mkdir -p deploy
        cp Dockerrun.aws.json deploy/Dockerrun.aws.json
        sed -i "s|\${ECR_REGISTRY}|public.ecr.aws/n1b7r8u0|g" deploy/Dockerrun.aws.json
        sed -i "s|\${ECR_REPOSITORY}|${{ secrets.ECR_REPOSITORY_NAME }}|g" deploy/Dockerrun.aws.json
        sed -i "s|\${IMAGE_TAG}|${{ github.sha }}|g" deploy/Dockerrun.aws.json
        cd deploy && zip -r deploy.zip .
